#!/usr/bin/python

# json converts json strips into data structures
# urllib2 makes the https request
import json, urllib2, datetime, sys, os
import subprocess
from os import system

# log
class log:
  # Constructor (open the file handle)
  def __init__ (self, file):
    self.file = file
    self.handle = open(file, "a")

  # Deconstructor (close the file handle)
  def __del__ (self): 
    self.pad()
    self.handle.close()

  # Write a message. This is the low level print function
  def write (self, msg): print >> self.handle, msg

  # Just write a message with a stamp
  def info (self, msg): 
    timestamp = "[%d/%d/%d %s:%s:%s] " % self.time()
    self.write(timestamp + msg)

  # Write an error to the log
  def error (self, msg): self.info("ERROR: " + msg)

  # Write a *BIG ERROR* to the log
  def bigerror (self, msg): self.info("***ERROR*** " + msg)

  # Write a warning to the log
  def warning (self, msg): self.info("Warning: " + msg)

  #
  def time (self):
    now = datetime.datetime.now()
    now = (now.month, now.day, now.year, now.hour, now.minute, now.second)
    return now

  # ..
  def pad (self, lines=2, string = "\n"): self.write(string * lines)


#
#
#
def is_r_package (path):

  if not os.path.isdir(path): return False

  R = os.path.join(path, "R")
  man = os.path.join(path, "man")
  DESCRIPTION = os.path.join(path, "DESCRIPTION")
  NAMESPACE = os.path.join(path, "NAMESPACE")

  goodfile = lambda x: os.path.isfile(x) and not os.path.islink(x)

  if not goodfile(DESCRIPTION): return False
  if not goodfile(NAMESPACE): return False
  if not os.path.isdir(R): return False
  if not os.path.isdir(man): return False

  return True


# parse options
user = "zeligdev"
url = "https://api.github.com/users/zeligdev/repos"


# directory variables
original_wd = os.getcwd()
clone_dir = "clone"
check_dir = "check"
build_dir = "repos"
destination = os.path.expanduser("~/Sites/src/contrib")


# Logger
zelig_build = log("zelig_build.log")
zelig_build.info("Staring up")


# make directories
try: 
  zelig_build.info("Creating directory " + clone_dir)
  os.mkdir(clone_dir)
except OSError: 
  zelig_build.info("Directory " + clone_dir + "already exists. Skipping")

try:
  zelig_build.info("Creating directory " + check_dir)
  os.mkdir(check_dir)
except OSError:
  zelig_build.info("Directory " + check_dir + "already exists. Skipping")

try:
  zelig_build.info("Creating directory " + build_dir)
  os.mkdir(build_dir)
except OSError:
  zelig_build.info("Directory " + build_dir + "already exists. Skipping")

#
if not os.path.exists(destination):
  zelig_build.info(
      "The destination repository directory (" + destination + ") must exist"
      )


# Get a response from the github api
# logger.info("Getting repository listing from zeligdev")
request = urllib2.Request(url)
response_stream = urllib2.urlopen(request)
response = response_stream.read()


# Program start
zelig_build.info("Getting list of repositories from " + url)


# Parses the repsonse into an actual data structure. Awesome!
repos = json.loads(response)


# Change working directory
os.chdir(clone_dir)


# Clone
for r in repos:
  pkg = r['name']
  url = r['git_url']

  pkg_dest = os.path.join(clone_dir, pkg)

  zelig_build.info("Cloning %s (%s)" % (url, pkg))
  result = subprocess.call("git clone %s %s" % (url, pkg), shell=True)

  if result == 0:
    zelig_build.info("Clone: Success")
  else:
    zelig_build.info("Clone: Fail")


# Change working directory
os.chdir(os.path.join(original_wd, check_dir))

# Check
# for r in repos:
#   pkg = r['name']
#   pkg = os.path.join("..", clone_dir, pkg)
# 
#   if not is_r_package(pkg):
#     zelig_build.info(pkg + " is not an R package. Skipping")
#     continue
# 
#   zelig_build.info(pkg + " is an R package")
#   zelig_build.info("Checking %s")
# 
#   # Run from the system's shell
#   result = subprocess.call("R CMD check %s" % pkg, shell=True)
# 
#   if result == 0:
#     zelig_build.info("Check: Success")
#   else:
#     zelig_build.info("Check: Fail")


# Change working directory
os.chdir(os.path.join(original_wd, build_dir))

# Build
for r in repos:
  pkg = r['name']
  pkg = os.path.join("..", clone_dir, pkg)

  zelig_build.info("Building %s" % pkg)

  # Run from the system's shell
  result = subprocess.call("R CMD build %s" % pkg, shell=True)

  # Move into the "REPOS" file
  # print tarball, "->", pkg_repos_dest
  # os.rename(tarball, pkg_repos_dest)

  if result == 0:
    zelig_build.info("Build: Success")
  else:
    zelig_build.info("Build: Fail")


# os.rename("*.tar.gz", )


os.chdir(original_wd)

try:
  os.renames(build_dir, destination)
except OSError:
  zelig_build.info("Moving packages")


# Create PACKAGES file
r_script = "tools:::write_PACKAGES()"
subprocess.call('"' + r_script + '"')
