#!/usr/bin/python

import json, httplib, urllib2

request = urllib2.Request("https://api.github.com/users/zeligdev/repos")
response_stream = urllib2.urlopen(request)
response = response_stream.read()

repos = json.loads(response)

git_urls = map(lambda x: x['clone_url'], repos)
for url in sorted(git_urls):
  print url
